[gcp_service_account]
type = "service_account"
project_id = "primerproyecto-465021"
private_key_id = "b04b921c48d8cffb0e8e7d50243150248ac39723"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDQlsltEf1ePatv
heQ6ynbb6a0fNmkBfknsauGEMkOur1oWrCo6aSVlqkILpqCdJeRF3EGWmTuxJZnC
yUcTuxqadfo6I47bdrlija3WJiJ4LofVVwyMW4sMUeIO1dPu4qNynqNLm8OPhtSn
epN51pPaRi7CYWlbfEv/nTzNv6kjBnXQVV/h7TjXTJHe7udnNInGQWvqX/DmJb6S
ar3nK8xawxQKgxZ4qkukei/T1H55/IQPQJd8N+ForHVtnzzsy+9F0+JVXrEhBV13
OKECQ1REdFGyD9I8BRe8OpFxttiJxQ6Oo2RKdV6LiSEPw/BK44OQW0RQKYxMyNJ0
3RvB9/H1AgMBAAECggEADX7WrRQJuLQJvaSZMG/oAnDFztariDleWV74P0rXPoaW
2rpXMxdEIFCZ3FIdYyglSEXTXTCF1aob9CfR+EYAlyIZ8fKvVqYBoY2Ow+O3aDTZ
J1BDU2jFgCMOGq1H/H/frlXy37ybXv5iD4Hqkmqef0lPfiu6RX0vF5cvQhVBQVmW
xVSAVjo8wkqJxW9aEB1g/XbqrGil8g0eYRfzTdaH2T0R3aKUlvNfBynTfrcwRx6M
kGYedklXQreE3HKZzFmacDq8cyrMDHrMqXYF8+/WF+VrlGXnQvvCuty50MnBql4C
31t7kCILPBoQS4rw6QaO16P9f8jSd+V7KWi+N/tq4QKBgQD/BjmJkGKk88XhaCG5
NgLrbQmmwhOx9F6NkX1nbwy1DK+fyJeGRFsY2WUV4NfYwjcprNBMeZeM+777a9P8
t8pP3FtsQjI5aoqSkijG4k4yqVyxqpmvCg6KcN5ouL9g0dQp845cCVvh/TBjWsFP
TZ9ToGDG2Orti3HDDdZEhSdP5QKBgQDRYxUgH4lKXtWLm1S7gwuyXLmombuqqVgn
7KvoU+0zMSlLI8vaVTdSRtmSdxYbGTJHUblOCOMSTSS5nTOS8aJAyMg0rKwY7XCr
04ByT/0PBsfCsgMDSzf3JPlnsVrl4qVHatnuEI/KDHEg8nKbb9RuWmjY3fQIHdPa
DDLEEzVY0QKBgF2h7XIifvVNQ3P1BZy4xe2mRQri6tRFgom7xy04ypOWqsyhm3CC
nGfNOZ4ExXsiI5q7hmbtpcTvkTlCZ7y7xh34K+DdlQ8bnPEflLUg1dEn+Y6Jso9f
w+L0edQ9MJbds2YLtFL6ZK/eg+uWoK77MupDUgTwE6FPt18EL41Mzhg5AoGBAKLS
G5FZNJdCW2guJ5uQcb4G4NA8i3RQLx8MqTkGWkMejW/CrDhhX515PqLoO6Zi13gi
EqidvIV0u4QivAIeJ/+coiJjy4euy5ix5QX/MVdH/HpnlnQvP5vNgquhfH+a2M9K
RaEb+9QwDKCEJ567PUN6xmEtZyAQobbDGY7jKO6hAoGAKuVL+2k7hoNljDqVt0Oo
QB/tgBsr44Yycdzle0emjT/wkuSIwW6UzzU7YzVOnRfXnvfb3UP+SaFqXFzdgvKX
dy+usAGRC6zSUVyCFli+XHh3sE0lpNhrsjsDTr6F99u/W1jWU50sNGdbnqy6ajQC
MVuzFBesqJvACX4yCRE83eE=
-----END PRIVATE KEY-----"""
client_email = "angel-122@primerproyecto-465021.iam.gserviceaccount.com"
client_id = "107069597140874852009"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/angel-122%40primerproyecto-465021.iam.gserviceaccount.com"
